#!/usr/bin/env bash
figlet decrypt
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls BUG*gpg)
do
  name=${file%%.gpg}
  uid=dindin_hernawan@yahoo.com
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls CHANGELOG*gpg)
do
  name=${file%%.gpg}
  uid=dindin_hernawan@yahoo.com
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls ORIGIN*gpg)
do
  name=${file%%.gpg}
  uid=dindin_hernawan@yahoo.com
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls PACKAGES*gpg)
do
  name=${file%%.gpg}
  uid=dindin_hernawan@yahoo.com
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls PURGE*gpg)
do
  name=${file%%.gpg}
  uid=dindin_hernawan@yahoo.com
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
